#!/usr/bin/env python3
"""
Interactive setup script for AI NarrativeFlow
Guides users through the configuration process
"""

import os
import sys
from pathlib import Path

def print_header(text):
    """Print a formatted header"""
    print("\n" + "="*60)
    print(f"  {text}")
    print("="*60 + "\n")

def print_step(step_num, text):
    """Print a numbered step"""
    print(f"[{step_num}] {text}")

def create_env_file():
    """Guide user through creating .env file"""
    print_header("Environment Configuration Setup")
    
    env_file = Path(".env")
    
    if env_file.exists():
        overwrite = input("✓ .env file exists. Overwrite? (y/n): ").lower()
        if overwrite != 'y':
            print("Keeping existing .env file.")
            return
    
    print("\n📝 Enter your Neon database connection string:")
    print("   (Get this from: https://console.neon.tech)")
    print("   Format: postgresql://user:password@ep-xxx.us-east-1.neon.tech/dbname")
    neon_url = input("\nNeon Database URL: ").strip()
    
    print("\n🤖 Enter your Ollama service URL:")
    print("   (Default: http://localhost:11434)")
    ollama_url = input("Ollama URL (press Enter for default): ").strip() or "http://localhost:11434"
    
    env_content = f"""# AI NarrativeFlow Configuration
# Auto-generated by setup script

# Neon PostgreSQL Database Connection
NEON_DB_URL={neon_url}

# Ollama Local LLM Configuration
OLLAMA_BASE_URL={ollama_url}
"""
    
    with open(env_file, 'w') as f:
        f.write(env_content)
    
    print(f"\n✅ Created .env file")

def check_dependencies():
    """Check if required Python packages are installed"""
    print_header("Checking Dependencies")
    
    required_packages = {
        'streamlit': 'Streamlit',
        'psycopg': 'PostgreSQL adapter',
        'requests': 'HTTP library',
        'dotenv': 'Environment loader'
    }
    
    missing = []
    
    for package, name in required_packages.items():
        try:
            __import__(package)
            print(f"✓ {name} is installed")
        except ImportError:
            print(f"✗ {name} is NOT installed")
            missing.append(package)
    
    if missing:
        print(f"\n⚠️  Missing packages: {', '.join(missing)}")
        install = input("\nInstall missing packages? (y/n): ").lower()
        if install == 'y':
            os.system("pip install -r requirements.txt")
            print("✅ Dependencies installed")
    else:
        print("\n✅ All dependencies are installed")

def check_neon_connection():
    """Check if Neon database is accessible"""
    print_header("Testing Neon Connection")
    
    try:
        import psycopg
        from dotenv import load_dotenv
        
        load_dotenv()
        neon_url = os.getenv("NEON_DB_URL")
        
        if not neon_url:
            print("❌ NEON_DB_URL not set in .env file")
            return False
        
        print("Attempting to connect to Neon database...")
        conn = psycopg.connect(neon_url)
        conn.close()
        print("✅ Successfully connected to Neon database")
        return True
        
    except Exception as e:
        print(f"❌ Failed to connect to Neon: {e}")
        print("\nTroubleshooting:")
        print("1. Verify your Neon connection string is correct")
        print("2. Check your internet connection")
        print("3. Ensure your Neon project is active")
        return False

def check_ollama():
    """Check if Ollama is running"""
    print_header("Testing Ollama Connection")
    
    try:
        import requests
        from dotenv import load_dotenv
        
        load_dotenv()
        ollama_url = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
        
        print(f"Checking Ollama at {ollama_url}...")
        response = requests.get(f"{ollama_url}/api/tags", timeout=2)
        
        if response.status_code == 200:
            models = response.json().get("models", [])
            if models:
                print(f"✅ Ollama is running with {len(models)} model(s)")
                for model in models:
                    print(f"   • {model['name']}")
            else:
                print("⚠️  Ollama is running but no models found")
                print("   Run: ollama pull mistral")
            return True
        else:
            print(f"❌ Ollama returned status {response.status_code}")
            return False
            
    except requests.exceptions.ConnectionError:
        print(f"❌ Cannot connect to Ollama at {ollama_url}")
        print("\nTroubleshooting:")
        print("1. Download Ollama from https://ollama.ai")
        print("2. Start the Ollama application")
        print("3. Pull Mistral model: ollama pull mistral")
        print("4. Verify it's running: curl http://localhost:11434/api/tags")
        return False
    except Exception as e:
        print(f"❌ Error checking Ollama: {e}")
        return False

def initialize_database():
    """Initialize the Neon database schema"""
    print_header("Initializing Database")
    
    try:
        # Import after checking dependencies
        import psycopg
        from dotenv import load_dotenv
        
        load_dotenv()
        neon_url = os.getenv("NEON_DB_URL")
        
        if not neon_url:
            print("❌ NEON_DB_URL not set")
            return False
        
        print("Creating database tables...")
        
        with psycopg.connect(neon_url) as conn:
            with conn.cursor() as cur:
                # Stories table
                cur.execute("""
                    CREATE TABLE IF NOT EXISTS stories (
                        id UUID PRIMARY KEY,
                        title TEXT NOT NULL,
                        description TEXT,
                        status TEXT CHECK (status IN ('drafting', 'outlining', 'editing')) DEFAULT 'drafting',
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        user_id TEXT NOT NULL DEFAULT 'default_user',
                        metadata JSONB DEFAULT '{}'::jsonb,
                        UNIQUE(user_id, title)
                    );
                """)
                print("  ✓ Created stories table")
                
                # Chapters table
                cur.execute("""
                    CREATE TABLE IF NOT EXISTS chapters (
                        id UUID PRIMARY KEY,
                        story_id UUID NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
                        chapter_num INTEGER NOT NULL,
                        title TEXT NOT NULL,
                        content TEXT,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        UNIQUE(story_id, chapter_num)
                    );
                """)
                print("  ✓ Created chapters table")
                
                # Narrative context table
                cur.execute("""
                    CREATE TABLE IF NOT EXISTS narrative_context (
                        id UUID PRIMARY KEY,
                        story_id UUID NOT NULL UNIQUE REFERENCES stories(id) ON DELETE CASCADE,
                        key_plot_points JSONB DEFAULT '[]'::jsonb,
                        character_arcs JSONB DEFAULT '{}'::jsonb,
                        thematic_elements JSONB DEFAULT '[]'::jsonb,
                        last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    );
                """)
                print("  ✓ Created narrative_context table")
                
                # Create indices
                cur.execute("CREATE INDEX IF NOT EXISTS idx_stories_user_id ON stories(user_id);")
                cur.execute("CREATE INDEX IF NOT EXISTS idx_chapters_story_id ON chapters(story_id);")
                print("  ✓ Created indices")
                
                conn.commit()
        
        print("\n✅ Database initialized successfully!")
        return True
        
    except Exception as e:
        print(f"❌ Error initializing database: {e}")
        return False

def run_interactive_setup():
    """Run the full interactive setup"""
    print_header("AI NarrativeFlow Setup Wizard")
    print("Welcome! This wizard will help you configure your AI story writing assistant.\n")
    
    # Step 1: Create .env
    create_env_file()
    
    # Step 2: Check dependencies
    check_dependencies()
    
    # Step 3: Test connections
    print_header("Testing Integrations")
    
    neon_ok = check_neon_connection()
    print()
    ollama_ok = check_ollama()
    
    # Step 4: Initialize database
    if neon_ok:
        print()
        init = input("Initialize database schema? (y/n): ").lower()
        if init == 'y':
            initialize_database()
    
    # Summary
    print_header("Setup Complete!")
    
    status = []
    status.append(f"Environment: ✓")
    status.append(f"Dependencies: ✓")
    status.append(f"Neon Database: {'✓' if neon_ok else '✗'}")
    status.append(f"Ollama LLM: {'✓' if ollama_ok else '✗'}")
    
    print("\nSetup Status:")
    for item in status:
        print(f"  {item}")
    
    print("\n🚀 Next Steps:")
    print("1. Start Ollama (if not already running)")
    print("2. Run: streamlit run app.py")
    print("3. Open http://localhost:8501 in your browser")
    
    print("\n📖 Documentation: See README.md for more details")
    print("\n✨ Happy writing!\n")

if __name__ == "__main__":
    run_interactive_setup()
